"""
WICKED Pipeline Orchestrator
Runs the 5-agent sequence: Trend Scout → Insight Analyst → Content Strategist
→ Script Writer → Brand Guardian.

Shared by the FastAPI endpoints (manual mode) and autonomous.py (loop mode).
"""

import logging
from datetime import datetime
from typing import Optional

from config import load_generated_scripts, save_generated_scripts
from models import (
    BrandGuardianOutput,
    GeneratedScript,
    PipelineRun,
    PipelineStatus,
    TrendScoutOutput,
)
from agents.trend_scout import TrendScoutAgent
from agents.insight_analyst import InsightAnalystAgent
from agents.content_strategist import ContentStrategistAgent
from agents.script_writer import ScriptWriterAgent
from agents.brand_guardian import BrandGuardianAgent

logger = logging.getLogger("wicked.pipeline")


def execute_pipeline(
    run: PipelineRun,
    precomputed_trend_output: Optional[TrendScoutOutput] = None,
) -> None:
    """
    Execute the full 5-agent pipeline synchronously, mutating `run` in place.

    If `precomputed_trend_output` is given (autonomous mode passes the already
    deduped Trend Scout result), Agent 1 is skipped to avoid a duplicate scan.
    """
    try:
        run.status = PipelineStatus.RUNNING
        inp = run.input
        logger.info("Pipeline %s started — topic: '%s'", run.id, inp.topic)

        # ── Agent 1: Trend Scout ──────────────────────────────
        if precomputed_trend_output is not None:
            trend_output = precomputed_trend_output
            logger.info(
                "[1/5] Trend Scout skipped — using %d precomputed trends",
                len(trend_output.trends),
            )
        else:
            logger.info("[1/5] Trend Scout scanning...")
            trend_scout = TrendScoutAgent(client_id=inp.client_id)
            trend_output = trend_scout.run(topic=inp.topic, keywords=inp.keywords)
            logger.info("[1/5] Trend Scout found %d trends", len(trend_output.trends))
        run.trend_output = trend_output

        # ── Agent 2: Insight Analyst ──────────────────────────
        logger.info("[2/5] Insight Analyst analyzing...")
        insight_analyst = InsightAnalystAgent(client_id=inp.client_id)
        insight_output = insight_analyst.run(trend_output)
        run.insight_output = insight_output
        logger.info("[2/5] Insight Analyst produced %d insights", len(insight_output.insights))

        # ── Agent 3: Content Strategist ───────────────────────
        logger.info("[3/5] Content Strategist creating concepts...")
        content_strategist = ContentStrategistAgent(client_id=inp.client_id)
        strategy_output = content_strategist.run(
            insight_output,
            content_format=inp.format,
            num_concepts=inp.num_concepts,
        )
        run.strategy_output = strategy_output
        logger.info("[3/5] Content Strategist created %d concepts", len(strategy_output.concepts))

        # ── Agent 4: Script Writer (use recommended concept) ──
        logger.info("[4/5] Script Writer writing...")
        if strategy_output.concepts:
            # Find the recommended concept, or use the first one
            chosen = strategy_output.concepts[0]
            for c in strategy_output.concepts:
                if c.id == strategy_output.recommended_concept_id:
                    chosen = c
                    break

            script_writer = ScriptWriterAgent(client_id=inp.client_id)
            script_output = script_writer.run(
                concept=chosen,
                style_reference=inp.style_reference,
            )
            run.script_output = script_output
            logger.info("[4/5] Script Writer completed: %s", script_output.script.title)

            # ── Agent 5: Brand Guardian ───────────────────────
            logger.info("[5/5] Brand Guardian reviewing...")
            brand_guardian = BrandGuardianAgent(client_id=inp.client_id)
            guardian_output = brand_guardian.run(script_output)
            run.guardian_output = guardian_output
            logger.info(
                "[5/5] Brand Guardian score: %.0f/100 — %s",
                guardian_output.overall_score,
                "APPROVED ✅" if guardian_output.approved else "NEEDS WORK ⚠️"
            )

            # Persist the script
            persist_script(script_output.script, guardian_output)
        else:
            logger.warning("[4/5] No concepts generated — skipping script writing.")
            run.error = "No content concepts were generated by the strategist."

        run.status = PipelineStatus.COMPLETED
        run.completed_at = datetime.utcnow()
        logger.info("Pipeline %s completed successfully!", run.id)

    except Exception as e:
        logger.error("Pipeline %s failed: %s", run.id, e, exc_info=True)
        run.status = PipelineStatus.FAILED
        run.error = str(e)
        run.completed_at = datetime.utcnow()


def persist_script(script: GeneratedScript, guardian: BrandGuardianOutput) -> None:
    """Save a generated script to the JSON persistence file / MongoDB."""
    try:
        scripts = load_generated_scripts()
        script_data = script.model_dump(mode="json")
        script_data["guardian_score"] = guardian.overall_score
        script_data["guardian_approved"] = guardian.approved
        scripts.append(script_data)
        save_generated_scripts(scripts)
        logger.info("Script persisted. Total scripts: %d", len(scripts))
    except Exception as e:
        logger.error("Failed to persist script: %s", e)
